// week2/taroapp/app/src/pages/login/index.jsx
import Taro, { Component } from '@tarojs/taro'
import { View } from '@tarojs/components'
import { AtInput, AtForm, AtButton } from 'taro-ui'
import { request } from './../../utils'
import './index.scss'

class Index extends Component {
  constructor (props) {
    super(props)
    this.state = {
      tel: '18813007814',
      password: '123456',
      telflag: false,
      passwordflag: false
    }
  }
  render () {
    return (
      <View>
        <AtForm>
          <AtInput
            error={ this.state.telflag }
            name='tel'
            clear
            title='手机号码'
            type='text'
            placeholder='手机号码'
            value={this.state.tel}
            onErrorClick={ () => {
              console.log('手机号码长度为11位')
              Taro.showToast({
                title: '手机号码长度为11位',
                icon: 'none',
                duration: 5000
              })
            }}
            onChange={ (value) => {
              console.log(value)
              let telflag = this.state.telflag
              if (value.length !== 11) {
                telflag = true
              } else {
                telflag = false
              }
              this.setState({
                tel: value,
                telflag
              })
            } }
          />
          <AtInput
            error={ this.state.passwordflag}
            name='password'
            title='密码'
            clear
            type='password'
            placeholder='密码'
            value={this.state.password}
            onErrorClick={ () => {
              console.log('密码长度应该大于6')
              Taro.showToast({
                title: '密码长度应该大于6',
                icon: 'none',
                duration: 5000
              })
            }}
            onChange={ (value) => {
              // let passwordflag = this.state.passwordflag
              // if (value.length < 6) {
              //   passwordflag = true
              // } else {
              //   passwordflag = false
              // }
              let flag = value.length < 6 ? true : false;
              this.setState({
                password: value,
                passwordflag: flag
              })
            }}
          />
          {/* <AtButton disabled={ this.state.tel.length !== 11 || this.state.password.length < 6 } type='secondary' size='normal'>登陆</AtButton> */}
          {/* 推荐使用下面写法，因为你的业务逻辑可能是复杂的正则验证 */}
          <AtButton disabled={ this.state.telflag || this.state.passwordflag } type= { this.state.telflag && this.state.passwordflag ? 'secondary' : 'primary'} size='normal' onClick={ () => {
            request({
              url: '/users/login',
              method: 'POST',
              data: {
                tel: this.state.tel,
                password: this.state.password
              },
              // 如果实际注册现实未注册，加上头信息
              header: {'content-type': "application/json; charset=utf-8"}
            }).then(res => {
              console.log(res)
              if (res.data.code === '10006') {
                Taro.showToast({
                  title: '用户未注册，请先注册',
                  icon: 'none',
                  duration: 3000
                })
              } else if (res.data.code === '10007') {
                Taro.showToast({
                  title: '密码错误',
                  icon: 'none',
                  duration: 3000
                })
              } else {
                Taro.showToast({
                  title: '登陆成功',
                  icon: 'none',
                  duration: 3000
                })

                try {
                  Taro.setStorageSync('userid', res.data.data.userid)
                  Taro.setStorageSync('token', res.data.data.token)
                  Taro.navigateBack()
                } catch (error) {
                  
                }
              }
            })
          } }>登陆</AtButton>
        </AtForm>
      </View>
    )
  }
}

export default Index

// week2/day01/uninz1914/pages/login/login.vue
<template>
	<view>
		<input type="text" v-model="tel" /> 
    <text :class="tel.length !== 11 ? 'error' : 'success'">{{ teltip }}</text>
    <input type="text" v-model="password">
    <text :class="password.length < 6 ? 'error' : 'success'">{{ passwordtip }}</text>
    <button 
    :disabled="tel.length !== 11 || password.length < 6"
    :type="tel.length === 11 && password.length >= 6 ? 'warn' : 'default'"
    @click="login"
    >登陆</button>
	</view>
</template>

<script>
  /**
   * 注册登录
   *  表单的展示形式  ---  用户体验
   */
  import { request, toast } from '../../utils/index.js'
	export default {
		data() {
			return {
				tel: '18813007814',
        password: '123456'
			}
		},
    computed: {
      teltip () {
        if (this.tel.length !== 11) {
          return '手机号码格式不正确'
        } else {
          return '手机号码ok'
        }
      },
      passwordtip () {
        if (this.password.length < 6) {
          return '密码格式不正确'
        } else {
          return '密码ok'
        }
      }
    },
		methods: {
      // 上面进行过 表单的检验，此处可以直接提交数据
			login () {
        request({
          url: '/users/login',
          method: 'POST',
          data: {
            tel: this.tel,
            password: this.password
          }
        }).then(res => {
          console.log(res.data)
          const { code } = res.data
          if (code === '10006') {
            toast({title: '该用户还未注册'})
          } else if (code === '10007') {
            toast({title: '密码错误'})
          } else {
            // 登陆成功
            toast({title: '登陆成功'})
            /**
             * 来到登陆页面的渠道
             *  用户在个人中心点击登陆按钮 ---- 返回个人中心页面
             *  点击详情的加入购物车的时候 ---- 返回详情页面
             *  点击浏览购物车的时候      ----  返回购物车页面
             *  注册进入登陆 使用的是重定向
             *  ........
             *  打哪儿来，去哪儿去
             * 
             *   token 验证用户的登陆状态
             *    将token信息存储在本地，以后在请求数据需要token时从本地获取，提交过去
             *    也可以将 用户的id 存储在本地
             * 
             *    uniapp 中如何使用本地存储
             * 
             */
            try {
              uni.setStorageSync('token', res.data.data.token)
              uni.setStorageSync('userid', res.data.data.userid)
              uni.navigateBack()
            } catch (e) {
              console.log(e)
            }
          }
        })
      }
		}
	}
</script>

<style>
.error {
  color: red;
}
.success {
  color: #4CD964;
}
</style>
