// week2/taroapp/app/src/pages/detail/index.jsx
import Taro, { Component } from '@tarojs/taro'
import { View, Image } from '@tarojs/components'
import { request } from './../../utils'
class Index extends Component {
  constructor (props) {
    super(props)
    this.state = {
      proid: '',
      proname: '详情',
      proimg: '',
      price: 0
    }
  }

  componentDidMount () {
    console.log(this.$router.params)
    const { proid } = this.$router.params
    request({
      url: '/pro/detail', // get请求的参数也可以放在data中
      data: {
        proid
      }
    }).then(res => {
      const { proname, proimg, price } = res.data.data
      this.setState({
        proname, proimg, price, proid
      })
      Taro.setNavigationBarTitle({
        title: proname
      })
    })
  }

  render () {
    return (
      <View>
        <Image src={ this.state.proimg }></Image>
        <View>{ this.state.proname }</View>
        <View>{ this.state.price }</View>
      </View>
    )
  }
}

export default Index

// week2/day01/uninz1914/pages/detail/detail.vue
<template>
	<view>
    <image :src="proimg" mode=""></image>
		<view>{{proname}}</view>
		<view>{{price}}</view>
	</view>
</template>

<script>
  import { request } from '../../utils/index.js'
	export default {
		data() {
			return {
				proname: '',
        proid: '',
        proimg: '',
        price: 0
			}
		},
    onLoad (options) {
       // console.log(options)
       const { proid } = options
       request({
         url:  `/pro/detail?proid=${proid}`
       }).then(res => {
         console.log(res.data.data)
         const { proname, proimg, price } = res.data.data
         this.proname = proname
         this.proimg = proimg
         this.price = price
         this.proid = proid
         uni.setNavigationBarTitle({
           title: proname
         })
       })
    },
		methods: {
			
		}
	}
</script>

<style>

</style>
